name: Android CI Pipeline

on:
  # Manual trigger
  workflow_dispatch:
  # Scheduled for 3am UTC every day except Sunday
  schedule:
    - cron: '0 3 * * 1-5' # 2:00 AM UTC
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Nightly Build
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
     - name: Checkout the Repository
       uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew build
